VERSION 0.7

IMPORT ../lib AS lib

test:
  FROM earthly/dind:alpine
  COPY docker-compose.yml ./
  COPY test ./test
  COPY +mitamae-tarball/mitamae.tar.gz ./build/mitamae.tar.gz
  WITH DOCKER --load systemd-ubuntu:latest=lib+systemd-ubuntu --compose docker-compose.yml
    RUN docker-compose exec -T instance /bin/bash -c "cd /root && tar zxvf /dev/shm/build/mitamae.tar.gz && cd ./mitamae && ./mitamae local roles/default.rb"
  END

original:
  FROM scratch
  GIT CLONE --branch c52b359fc6e733e1193ac8e9835bea23856566e7 https://github.com/isucon/isucon13.git original
  SAVE ARTIFACT original

bench:
  FROM golang:1.21.3-alpine3.18
  COPY +original/original/bench /build/bench
  WORKDIR /build/bench
  RUN GOOS=linux GOARCH=amd64 go build -buildvcs=false -o bench ./cmd/bench
  SAVE ARTIFACT bench

mitamae-tarball:
  FROM alpine:3.18
  RUN apk add patch
  COPY mitamae /mitamae
  COPY lib+mitamae-bin/mitamae /mitamae/mitamae
  COPY +bench/bench /mitamae/cookbooks/bench/files/opt/bench/bench
  RUN tar czvf mitamae.tar.gz mitamae/
  SAVE ARTIFACT /mitamae.tar.gz AS LOCAL build/mitamae.tar.gz
